src/ShooppyMegaMall.UI/Controllers/AuthenticationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ShooppyMegaMall.Application.Models;
using ShooppyMegaMall.UI.Helpers;
using ShooppyMegaMall.UI.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace ShooppyMegaMall.UI.Controllers
{
    [DataContract]
    public class AuthenticationsController : BaseController
    {
        private readonly IAuthenticationsPageService _AuthenticationPageService;
        private readonly ICommonHelper _commonHelper;
        private readonly IHostingEnvironment _hostingEnvironment;

        public AuthenticationsController(IAuthenticationsPageService AuthenticationPageService, IHostingEnvironment hostingEnvironment, ICommonHelper commonHelper)
        {
            _AuthenticationPageService = AuthenticationPageService ?? throw new ArgumentNullException(nameof(AuthenticationPageService));
            _hostingEnvironment = hostingEnvironment;
            _commonHelper = commonHelper;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Login(int orgid)
        {
            orgid = _commonHelper.GetOrgID(HttpContext);
            var logo = await _AuthenticationPageService.Get_Logo(orgid);
            return View(logo);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
        //[HttpPost, AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Login(UsersModal usersModal)
        //{
        //    usersModal.OrgId = commonHelper.GetOrgID(HttpContext);
        //    var UserValidate = await _AuthenticationPageService.Get_Login_Data(usersModal.Username, usersModal.Password, (int)usersModal.OrgId);
        //    if (UserValidate.Password != null && UserValidate.Username != null)
        //    {
        //        _ = CreateAuthenticationTicket(UserValidate);

        //        return RedirectToAction("Index", "Home", new { area = "" });
        //    }
        //    else
        //    {
        //        ViewBag.LoginValidError = "Username or Password is Incorrect";
        //    }
        //    return View(UserValidate);
        //}   public async Task<ActionResult> Login([FromBody] LoginCheckModel loginCheckModel)             var UserValidate = await _AuthenticationPageService.Get_Login_Data(loginCheckModel.datal.userid,loginCheckModel.datal.password,OrgId);


        [HttpPost, AllowAnonymous]
        public async Task<ActionResult> Login(UsersModal usersModal)
        {
            if (usersModal != null)
            {

               // int OrgId = _commonHelper.GetOrgID(HttpContext);
                var UserValidate = await _AuthenticationPageService.Get_Login_Data(usersModal.Email, usersModal.Password);
                if (UserValidate.Password != null && UserValidate.Email != null)
                {
                    await CreateAuthenticationTicket(UserValidate);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["LoginValidError"] = "Username or Password is Incorrect";
                }
            }
            else
            {
              TempData["LoginValidError"] = "User Not Found Please Sign Up";
            }
            //return RedirectToAction("Index","Home", new { area = "" });
            return View(usersModal);
        }


        [HttpPost, AllowAnonymous]
        public async Task<ActionResult> UserExistLogin(UsersModal usersModal)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            var UserValidate = await _AuthenticationPageService.Get_Exist_Login_Data(usersModal.Exist_Email, usersModal.Exist_Password, OrgId);
            if (UserValidate.Password != null && UserValidate.Email != null)
            {
                await CreateAuthenticationTicket(UserValidate);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["LoginValidError"] = "Username or Password is Incorrect";
            }
            //return RedirectToAction("Index","Home", new { area = "" });
            return View("Login", usersModal);
        }

        public async Task<IActionResult> Register()
        {
            return View();
        }

        [HttpPost, AllowAnonymous]
        public async Task<ActionResult> Register(UsersModal usersModal)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            //if(usersModal.Username)
          var Register = await _AuthenticationPageService.RegisterDetail(usersModal.Username,usersModal.Password,usersModal.Email,OrgId);
        
            if (Register == null)
                return RedirectToAction("Login");
              
            else
                TempData["SignValidError"] = "Email is already exsist";
            //return RedirectToAction("Index","Home", new { area = "" });
            // return Json(loginCheckModel);

            return View(usersModal);
        }

        public async Task<IActionResult> ForgotPassWord()
        {
            return View();
        }

        [HttpPost, AllowAnonymous]
        public async Task<ActionResult> ForgotPassWord(UsersModal usersModal)
        {
            if(usersModal.Password == usersModal.ConfPassword)
            {
                int OrgId = _commonHelper.GetOrgID(HttpContext);
                var ForgotPass = await _AuthenticationPageService.ForgotPass(usersModal.Password, usersModal.Email, OrgId);

                if (ForgotPass == null)
                    TempData["EmailValidError"] = "Email not found";
                else
                    return RedirectToAction("Login");
            }
            else
            {
                TempData["PassValidError"] = "Password and Confirm Password not match.";
            }
            
            return View();
        }
    }
}

src/ShooppyMegaMall.UI/Controllers/MyAccountController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using ShooppyMegaMall.Application.Models;
using ShooppyMegaMall.UI.Extensions;
using ShooppyMegaMall.UI.Helpers;
using ShooppyMegaMall.UI.Interfaces;
using ShooppyMegaMall.Web.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ShooppyMegaMall.UI.Controllers
{
    [Authorize]
    public class MyAccountController : Controller
    {
        private EncryptionHelper eh = new EncryptionHelper();
        private readonly IConfiguration _config;
        private readonly IBrandPageServices _brandPageService;
        private readonly ICategoryPageService _categoryPageService;
        private readonly IMyAccountPageService _myAccountPageService;
        private readonly ILogger<MyAccountController> _logger;
        private readonly ICommonHelper _commonHelper;
        private readonly IHostingEnvironment hostingEnvironment;

        public MyAccountController(IConfiguration config, IHostingEnvironment hostingEnvironment, IBrandPageServices brandPageServices, IMyAccountPageService myAccountPageServices, ICategoryPageService categoryPageService, ILogger<MyAccountController> logger, IWishlistPageService productPageService, IHttpContextAccessor accessor, ICommonHelper commonHelper)
        {
            _myAccountPageService = myAccountPageServices ?? throw new ArgumentNullException(nameof(myAccountPageServices));
            _categoryPageService = categoryPageService ?? throw new ArgumentNullException(nameof(categoryPageService));
            _brandPageService = brandPageServices ?? throw new ArgumentNullException(nameof(brandPageServices));
            _logger = logger ?? throw new ArgumentNullException();
            _commonHelper = commonHelper;
            _config = config;
            this.hostingEnvironment = hostingEnvironment;
        }
        [HttpGet]
        public async Task<IActionResult> myAccount(int profileId,int CategoryId)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            int Profileid = await _myAccountPageService.GetProfileId(User.Identity.Name,OrgId);
            var brands = await _brandPageService.GetBrands(OrgId);
            brands.Categories = await _categoryPageService.GetCategories(CategoryId, OrgId);
            brands.CategoryMaster = await _categoryPageService.DisplayLogo(OrgId);
            brands.ProductsDetails = await _categoryPageService.GetProductList(OrgId);
            brands.Myaccount = await _myAccountPageService.GetMyAccountDetail(OrgId, Profileid);
            return View(brands);
        }
        [HttpGet]
        public async Task<IActionResult> EditProfile(int CategoryId)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            int Profileid = await _myAccountPageService.GetProfileId(User.Identity.Name,OrgId);
            var brands=await _myAccountPageService.GetProfileByProfileId(Profileid);
            brands.CategoryMaster = await _categoryPageService.DisplayLogo(OrgId);
            brands.Categories = await _categoryPageService.GetCategories(CategoryId, OrgId);
            brands.ProductsDetails = await _categoryPageService.GetProductList(OrgId);
            brands.Myaccount = await _myAccountPageService.GetMyAccountDetail(OrgId, Profileid);
            return View(brands);
        }
        [HttpPost]
        public async Task<IActionResult> EditProfile(MainModel account)
        {
            //int OrgId = commonHelper.GetOrgID(HttpContext);
            //account.OrgId = OrgId;
            // account.ProfileId = await _myAccountPageService.GetProfileId(User.Identity.Name);


                if (account.ProfileImage != null)
                {
                    account.CoverImage = await UploadProfileImage(account);
                }
                await _myAccountPageService.UpdateMyAccountDetail(account);
            
                return View(account);
        }
        [HttpGet]
        public async Task<IActionResult> ChangePassword(int CategoryId, int ProfileId)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            int Profileid = await _myAccountPageService.GetProfileId(User.Identity.Name,OrgId);
            var brands = await _myAccountPageService.GetProfileByProfileId(Profileid);
            brands.CategoryMaster = await _categoryPageService.DisplayLogo(OrgId);
            brands.Categories = await _categoryPageService.GetCategories(CategoryId, OrgId);
            brands.ProductsDetails = await _categoryPageService.GetProductList(OrgId);
            brands.Myaccount = await _myAccountPageService.GetMyAccountDetail(OrgId, Profileid);
            return View(brands);
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(MainModel model)
        {
             // string Password = model.Password;             \\
            // string encryptedpassword = eh.Encrypt(Password);\\
           //  model.Password = encryptedpassword;              \\
          // model.UserId = 2116;                                \\
            await _myAccountPageService.ChangePassword(model);
            return View(model);
        }
        private async Task<string> UploadProfileImage(MainModel account)
        {
            string productimg = string.Empty;
            string Image = string.Empty;
            try
            {
                AWS_Helper aws = new AWS_Helper(_config, hostingEnvironment);
                productimg = _config.GetSection("AWSAppSettings")["awsfolderkey"] + account.OrgId + _config.GetSection("AWSAppSettings")["Products"];
                if (account.ProfileImage != null)
                {
                    Image = productimg + "File_" + Path.GetFileNameWithoutExtension(account.ProfileImage.FileName) + '_' + DateTime.Now.ToString("yyyyMMddHHmm") + Path.GetExtension(account.ProfileImage.FileName);
                    return await aws.uploadfile(account.ProfileImage, productimg);

                }

                return _config.GetSection("AWSAppSettings")["AwsMain_Link"] + Image;
            }
            catch (Exception e)
            {
                _commonHelper.LogError(e.Message);
                throw e;
            }
        }

    }
}

src/ShooppyMegaMall.UI/Views/MyAccount/ChangePassword.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
@model ShooppyMegaMall.Application.Models.MainModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<div class="main-area">
    <div class="contact-page-area">
        <div class="container-fluid">
            <div class="contact-from-atea">
                <div class="form-and-info">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="contactDetails contactHead">
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="contactfrom">
                                <h1>Change Password</h1>
                                <form method="post" enctype="multipart/form-data" asp-controller="MyAccount" asp-action="ChangePassword">
                                    <input type="hidden" asp-for="UserId" />
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <input type="password" asp-for="@Model.Password" placeholder="password" id="Password" class="form-control">
                                            <span asp-validation-for="@Model.Password" class="text-danger" id="mypwdmsg"></span>
                                        </div>
                                        <div class="col-lg-12">
                                            <input type="password" asp-for="@Model.CPassword" style="margin-top:10px;" placeholder="Confirm password" id="cpassword" class="form-control">
                                            <span asp-validation-for="@Model.CPassword" class="text-danger" id="mycpwdmsg"></span>
                                        </div>
                                    </div>
                                    <button style="margin-top:20px;" class="btn btnContact" type="submit" name="changepassbtn">Change Password</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

src/ShooppyMegaMall.UI/Views/MyAccount/EditProfile.cshtml
@model ShooppyMegaMall.Application.Models.MainModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<div class="main-area">
    <div class="contact-page-area">
        <div class="container-fluid">
            <div class="contact-from-atea">
                <div class="form-and-info">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="contactfrom">
                                <h1>Edit Profile</h1>
                                <form asp-controller="MyAccount" asp-action="EditProfile" method="post" enctype="multipart/form-data">
                                    <input type="hidden" asp-for="ProfileId" />
                                    <input type="hidden" asp-for="CoverImage" />
                                    <input type="hidden" asp-for="OrgId" />
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <input type="text" asp-for="@Model.UserName" placeholder="UserName" id="UserName" class="form-control">
                                        </div>
                                        <div class="col-lg-6">
                                            <input type="text" asp-for="@Model.ContactNumber" placeholder="Contact Number" id="ContactNumber" class="form-control">
                                            <span asp-validation-for="@Model.ContactNumber" class="text-danger field-validation-valid"></span>
                                        </div>
                                        <div class="col-lg-4">
                                            <input type="text" asp-for="@Model.City" placeholder="City" id="City" class="form-control">
                                        </div>
                                        <div class="col-lg-4">
                                            <input type="text" asp-for="@Model.State" placeholder="State" id="State" class="form-control">
                                        </div>
                                        <div class="col-lg-4">
                                            <input type="text" asp-for="@Model.Country" placeholder="Country" id="Country" class="form-control">
                                        </div>
                                        <div class="col-lg-12">
                                            <textarea placeholder="Address" asp-for="@Model.Address" rows="8" class="form-control"></textarea>
                                        </div>
                                        <div class="col-lg-12">
                                            <a class="btn btnpwd" style="margin-bottom: 15px" asp-action="ChangePassword" name="changepass">Change Password</a>
                                        </div>
                                        <div class="col-lg-12">
                                            <label class="btn btnimg">
                                                Select Image
                                                <input asp-for="ProfileImage" id="img" accept="image/jpg,image/jpeg,image/png" hidden />
                                            </label>
                                            <img id="imgPreview" src="@Url.Content("~")@Model.CoverImage" alt="yourprofileimage" loading="lazy" style="max-height: 80px; max-width: 80px; margin-left: 25px" />
                                            <span asp-validation-for="ProfileImage" id="imageval" class="text-danger "></span>
                                            <div id="msg" style="color:red;">
                                                @ViewBag.message
                                            </div>
                                        </div>
                                    </div>
                                    <button style="margin-top:25px;" class="btn btnContact" type="submit" name="profileupdatebtn">Update Profile</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(() => {
        $('#img').change(function () {
            const file = this.files[0];
            if (file) {
                let reader = new FileReader();
                reader.onload = function (event) {
                    console.log(event.target.result);
                    $('#imgPreview').attr('src', event.target.result);
                }
                reader.readAsDataURL(file);
            }
            var fileInput = document.getElementById('img');
            var filePath = fileInput.value;
            // Allowing file type
            var allowedExtensions = /(\.jpg|\.jpeg|\.png|\.gif)$/i;
            if (!allowedExtensions.exec(filePath)) {
                document.getElementById("imageval").innerHTML = "Invalid image Type";
                fileInput.value = '';
                return false;
            }
            else {
                document.getElementById("imageval").innerHTML = "";
            }
        });
    });
</script>

src/ShooppyMegaMall.UI/Views/MyAccount/myAccount.cshtml
@model ShooppyMegaMall.Application.Models.MainModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<link href="~/css/MyAcLogButton.css" rel="stylesheet" />
<div class="main-area">
    <div class="contact-page-area">
        <div class="container-fluid">
            <div class="contact-from-atea">
                <div class="form-and-info">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="contactDetails contactHead">
                                <h3>CONTACT Info</h3>

                                @foreach (var Account in Model.Myaccount)
                                {
                                    <p>
                                        <span class="iconContact"><i class="fa fa-map-marker"></i></span>
                                        @Account.Address
                                    </p>
                                    <p>
                                        <span class="iconContact"><i class="fa fa-phone"></i></span>
                                        @Account.ContactNumber
                                    </p>
                                    <p>
                                        <span class="iconContact"><i class="fa fa-envelope"></i></span>
                                        Email:@Account.Email
                                    </p>
                                }
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="contactfrom">
                                @*@foreach (var myaccount in Model.Myaccount.Take(1))
                                {*@
                                <h1>My Profile</h1>

                               @foreach (var Account in Model.Myaccount)
                                {
                                    <img src="@Account.CoverImage" loading="lazy" alt="yourcoverimg" style="margin-right: 55px;max-height:100px; float: right;" />
                                    <form action="#">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <input type="text" asp-for="@Account.UserName" readonly id="UserName" class="form-control">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-6 contactemail">
                                                <input type="email" asp-for="@Account.Email" readonly id="Email" class="form-control">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-6 cart-checkout">
                                                <a class="text-decoration-none" asp-controller="MyAccount" asp-action="EditProfile" name="editpro">Edit Profile &nbsp;<i class="fa fa-pen"></i></a>
                                            </div>
                                            <div class="col-6 cart-checkout" id="fadeshow1">
                                                <a class="text-decoration-none" asp-action="Logout" asp-controller="Authentications" name="logout">Logout<i class="fa fa-sign-out-alt"></i></a>
                                            </div>
                                        </div>
                                    </form>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>