src/ShooppyMegaMall.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShooppyMegaMall.Application.Models;
using ShooppyMegaMall.UI.Extensions;
using ShooppyMegaMall.UI.Helpers;
using ShooppyMegaMall.UI.Interfaces;
using ShooppyMegaMall.Web.Interfaces;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShooppyMegaMall.UI.Controllers
{
    public class HomeController : Controller
    {
        private IHttpContextAccessor _accessor;
        private readonly ILogger<HomeController> _logger;
        private readonly IBrandPageServices _BrandPageService;
        private readonly IWishlistPageService _wishlistPageService;
        private readonly ICategoryPageService _categoryPageService;
        private readonly ICommonHelper _commonHelper;

        public HomeController(IBrandPageServices brandPageServices, ILogger<HomeController> logger, ICategoryPageService categoryPageService, IHttpContextAccessor accessor,IWishlistPageService wishlistPageService, ICommonHelper commonHelper)
        {
            _accessor = accessor;
            _logger = logger ?? throw new ArgumentNullException();
            _BrandPageService = brandPageServices ?? throw new ArgumentNullException(nameof(brandPageServices));
            _categoryPageService = categoryPageService ?? throw new ArgumentNullException(nameof(categoryPageService));
            _wishlistPageService = wishlistPageService ?? throw new ArgumentNullException(nameof(wishlistPageService));
            _commonHelper = commonHelper;
        }
        public async Task<IActionResult>Index(int CategoryId)
        {
            int OrgId  = _commonHelper.GetOrgID(HttpContext);
            var brands = await _BrandPageService.GetBrands(OrgId);
            brands.CategoryMaster =  await _categoryPageService.DisplayLogo(OrgId);
            brands.MiddelBanner = await _categoryPageService.GetMiddelBannerImage(OrgId);
            brands.TopBanner = await _categoryPageService.GetTopBannerImage(OrgId);
            brands.ProductsDetails = await _categoryPageService.GetProductList(OrgId);
            brands.Categories = await _categoryPageService.GetCategories(CategoryId,OrgId);
            brands.BottomBanner = await _categoryPageService.GetBottomBanner(OrgId);
            brands.BannersByCategory = await _categoryPageService.GetBannerByCategory(OrgId);
            brands.CategoryBanner = await _categoryPageService.GetCategoryBannerImage(OrgId);
            brands.LeftBanner = await _categoryPageService.GetLeftBanner(OrgId);
            return View(brands);
        }
        public async Task<IActionResult> ProductsByBrand(int CategoryId,int BrandId)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            var brands = await _BrandPageService.GetBrands(OrgId);
            brands.CategoryMaster = await _categoryPageService.DisplayLogo(OrgId);
            brands.MiddelBanner = await _categoryPageService.GetMiddelBannerImage(OrgId);
            brands.TopBanner = await _categoryPageService.GetTopBannerImage(OrgId);
            brands.ProductsDetails = await _categoryPageService.GetProductList(OrgId);
            brands.Categories = await _categoryPageService.GetCategories(CategoryId, OrgId);
            brands.BottomBanner = await _categoryPageService.GetBottomBanner(OrgId);
            brands.BannersByCategory = await _categoryPageService.GetBannerByCategory(OrgId);
            brands.CategoryBanner = await _categoryPageService.GetCategoryBannerImage(OrgId);
            brands.LeftBanner = await _categoryPageService.GetLeftBanner(OrgId);
            brands.ProductdByBrand = await _BrandPageService.GetProductsByBrand(OrgId, BrandId);
            return View(brands);
        }
        //public async Task<IActionResult> PageNotFound()
        //{
        //    int OrgId = _commonHelper.GetOrgID(HttpContext);
        //    if (OrgId == 0)
        //    {
        //        return View();
        //    }
        //    return RedirectToAction("Index");
        //}

        [HttpGet]
        public async Task<JsonResult> Get_Product_By_Cat(int ID)
        {
           var AA = await _BrandPageService.Get_Product_By_Cat(ID);
            return Json(AA.f_getproducts_By_CatIdModel);
        }
        public async Task<IActionResult> AllProducts(int CategoryId)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            var brands = await _BrandPageService.GetBrands(OrgId);
            brands.CategoryMaster = await _categoryPageService.DisplayLogo(OrgId);
            brands.ProductsDetails = await _categoryPageService.GetProductList(OrgId);
            brands.Categories = await _categoryPageService.GetCategories(CategoryId, OrgId);
            brands.Product_specification = await _categoryPageService.GetAllProductByCategory(CategoryId,OrgId);
            if (User.Identity.Name != null)
            {
              brands.Wishlists = await _wishlistPageService.GetWishList(User.Identity.Name, OrgId);
            }

            brands.Attributes = await _categoryPageService.GetAllAttributes(OrgId);
            brands.AllCategories = await _categoryPageService.GetAllCategories(OrgId);
            return View(brands);
        }
        [HttpGet]
        public async Task<IActionResult> _ProductsByAttribute(int CategoryId, string SpecificationName)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            MainModel model = new MainModel();
            if(SpecificationName!=null)
            {
                model.Product_specification = await _categoryPageService.GetAllProductByAttribute(CategoryId, SpecificationName);
            }
            else
            {
                model.Product_specification = await _categoryPageService.GetAllProductByCategory(CategoryId,OrgId);
            }
            return PartialView(model);
        }

        [HttpGet]
        public async Task<IActionResult> News_Letter_Submit(string email)
        {
            if (email == null || email == "")
            {
                TempData["EmailError"] = "Please Enter Email";
            }
            else
            {
                int orgid = _commonHelper.GetOrgID(HttpContext);
                await _BrandPageService.News_Letter_Submit(orgid, email);
                TempData["EmailError"] = "You Successfully Subscribed to our NewsLetter !!";
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> SearchProduct(string SearchKey)
        {
            int orgid = _commonHelper.GetOrgID(HttpContext);

            var SearchResult = await _BrandPageService.SearchProduct(SearchKey,orgid);
            return View(SearchResult);
        }
        public  ActionResult TermsAndCondition()
        {
            return View();
        }
        public ActionResult PrivacyPolicy()
        {
            return View();
        }
        public ActionResult MerchantTermsAndCondition()
        {
            return View();
        }
        public ActionResult MerchantPrivacyPolicy()
        {
            return View();
        }
        public ActionResult MerchantRefundPolicy()
        {
            return View();
        }
        public ActionResult ShippingPolicy()
        {
            return View();
        }
    }
}

src/ShooppyMegaMall.UI/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShooppyMegaMall.Application.Models;
using ShooppyMegaMall.UI.Helpers;
using ShooppyMegaMall.UI.Interfaces;
using ShooppyMegaMall.UI.Models;
using ShooppyMegaMall.Web.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShooppyMegaMall.UI.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IproductDetailPageServices _ProductDetailPageService;
        private readonly IWishlistPageService _productWishListService;

        //private readonly ICategoryPageService _categoryPageService;
        private readonly ICommonHelper _commonHelper;


        
        public ProductDetailController(ILogger<HomeController> logger, IproductDetailPageServices categoryPageService, ICommonHelper commonHelper, IWishlistPageService productWishListService)
        {
            _logger = logger ?? throw new ArgumentNullException();
            _ProductDetailPageService = categoryPageService ?? throw new ArgumentNullException(nameof(categoryPageService));
            _commonHelper = commonHelper;
            _productWishListService = productWishListService;

            //_categoryPageService = categoryPageService ?? throw new ArgumentNullException(nameof(categoryPageService));
        }

        public IActionResult Index()
        {
            return View();
        }

        // [HttpPost]
        public async Task<IActionResult> Details(Guid id)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            string userName = User.Identity.Name;
            int orgid = _commonHelper.GetOrgID(HttpContext);         
            var Product_Details = await _ProductDetailPageService.GetProductDetails(id, orgid, userName);
            if (Product_Details.ProductPriceModel != null)
                Product_Details.ProductPriceModel.Price = Product_Details.ProductPriceModel.Price + Product_Details.ProductPriceModel.DeliveryFees;
            if (userName!=null)
            {
                Product_Details.Wishlists = await _productWishListService.GetWishList(userName, OrgId);
            }
            return View(Product_Details);
        }

        [HttpPost]
        public async Task<ActionResult> Product_Spcification_Details([FromBody]GetSpecModel get )
        {
            Guid guid = Guid.Parse(get.Guid);
            int orgid = Convert.ToInt32(get.Orgid);
            int SpecId = Convert.ToInt32(get.SpecId);
            get.Is_In_WishList = false;
            string userName = User.Identity.Name;
            decimal price = 0;
            int Qty = 0;
            var CheckWishlist = new List<Customer_WishlistModel>();
            var Product_Varients = await _ProductDetailPageService.GetProductVarient(guid,orgid,SpecId);
            if (userName != null)
            {
               CheckWishlist = await _productWishListService.GetWishList(userName, orgid);
                if(CheckWishlist != null)
                {
                    foreach(var WishList in CheckWishlist.Where(x=>x.SpecificationId == SpecId))
                    {
                        get.Is_In_WishList = true;
                    }
                }
            }

            try
            {
               foreach(var Spec in Product_Varients)
               {
                   get.Image = Spec.Image;
                   get.name = Spec.SpecificationNames;
                   price = Spec.Price;
                    Qty = Spec.Quantity;
               }
            }
            catch (Exception e) 
            {
                throw e;
            }    

            get.Price = price;
            get.Qty = Qty;

            if(price == 0)
            {
                return Json("nothing");
            }

            return Json(get);
        }
        public async Task<IActionResult> AddToWhishList(int ProductId,Guid id,int Specid)
        {
            int OrgId = _commonHelper.GetOrgID(HttpContext);
            MainModel mainModel = new MainModel();
            mainModel.ProductId = ProductId;
            mainModel.OrgId = OrgId;
            mainModel.SpecId = Specid;
            mainModel.guid = id;

            await _productWishListService.AddtowhishList(mainModel);
            return RedirectToAction("Details",new {id = id});
        } 

        [HttpGet]
        public async Task<IActionResult> AddProductToCart(ProductDetailModel productDetailModel)
        {
            try
            {
                await _ProductDetailPageService.AddToCart(productDetailModel);
                return RedirectToAction("Details", new { id = productDetailModel.ProductBasicModel.ProductGuid });
            }
            catch (Exception)
            {

                throw;
            }
            
        } 

        public async Task<IActionResult>BuyNow(ProductDetailModel productDetailModel)
        {
            try
            {
                var Buy = await _ProductDetailPageService.BuyNow(productDetailModel);
                return RedirectToAction("CheckOut", "Cart", new { orderid = Buy.OrderBasicModel.OrderGuid });
            }
            catch (Exception)
            {

                throw;
            }
           
        }
         
        public async Task<IActionResult>Add_Specification_ToCart(ProductDetailModel productDetailModel)
        {
            try
            {
                await _ProductDetailPageService.Addto_Spec_Product(productDetailModel);

                return RedirectToAction("Details", new { id = productDetailModel.ProductBasicModel.ProductGuid });
            }
            catch (Exception e)
            {

                throw e;
            }
           
        }

        public async Task<IActionResult> Add_Specification_BuyNow(ProductDetailModel productDetailModel)
        {
            try
            {
                var Buy_Now = await _ProductDetailPageService.BuyNow_Spec_Product(productDetailModel);

                return RedirectToAction("CheckOut", "Cart", new { orderid = Buy_Now.OrderBasicModel.OrderGuid });
            }
            catch (Exception e)
            {

                throw e;
            }
           
        }
    }
}

src/ShooppyMegaMall.UI/Views/Home/Index.cshtml
@model ShooppyMegaMall.Application.Models.MainModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Shooppy Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .theme-default img {
        max-height: 350px;
    }
    .shrink img {
        transition: 1s ease;
    }
        .shrink img:hover {
            -webkit-transform: scale(0.8);
            -ms-transform: scale(0.8);
            transform: scale(0.8);
            transition: 1s ease;
        }
    .img-hover-zoom {
        overflow: hidden; /* [1.2] Hide the overflowing of child elements */
    }
        .img-hover-zoom img {
            transition: transform .5s ease;
        }
        .img-hover-zoom:hover img {
            transform: scale(1.5);
        }
    .image {
        flex-shrink: 0;
    }
</style>
<div class="slider-area">
    <div class="container-fluid">
        <div class="slider">
            <div id="container">
                <!-- Nivo slider Demo 35 -->
                <div id="NivosliderD35oo slider-gray-bg">
                    <div class="nivoSlider theme-default">
                        @await Html.PartialAsync("_TopBanner", Model)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pt-4">
    <div class="container-fluid">
        <div class="row">
            @await Html.PartialAsync("_MiddelBanner", Model)
        </div>
    </div>
</div>
<!-- End baner area -->
@await Html.PartialAsync("_ProductWithCatId")
@await Html.PartialAsync("_ProductWithStatusId")
@await Html.PartialAsync("_GetRecentProduct")
@await Html.PartialAsync("_BottomBanner")
@await Html.PartialAsync("_BrandZone")
@*<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script>
        $(document).ready(function () {
            //$('#loader').css('display', 'none');
          //  $('#wrapper').css('display', 'block');
            $(".container").attr("style", "display:none");
        });
        $(window).on('load', function () {
          //  $(".slider-area").attr
            $(".containers").fadeOut("slow");
           // $(".container").remove.attr("style", "display:initial");
            $(".container").removeAttr("style", "display:none");
        });
    </script>*@
<script>
    $('#removewishlist').hide();
    $('.addWish').click(function (e)
    {
        if ($(e.target).css('color') == 'rgb(255, 0, 0)')
        {
            $(e.target).css('color', 'white');
        }
        else
        {
            $(e.target).css('color', 'red');
        }
      e.preventDefault();
  var el = $(this),
    icon = el.find('i'),
            productId = el.data("product")
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Wishlist", "Wishlist")',
            data: {
                "id": productId
            },
            success: function (data) {
        }
        });
    });
</script>

src/ShooppyMegaMall.UI/Views/Home/MerchantPrivacyPolicy.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Privacy Policy</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/StyleSheet1.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="pp-title">@ViewBag.OrganizationName Privacy & Policy</h1>

        <p>The privacy policy refers to how we "Shooppy (Ashok Infotech)" uses and protects any information you provide on our website and app. We make sure your information is protected and used in a rightful manner.</p>
        <h5>PERSONAL INFORMATION WE COLLECT:</h5>
        <strong>Device Information:</strong>
        <p>
            When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. This information is collected automatically.
        </p>
        <strong>Order Information:</strong>
        <p>
            Additionally, when you make a purchase or attempt to make a purchase through the Site, we collect certain information from you, including your name, billing address, shipping address, payment information, email address, and phone number.
            When we talk about "Personal Information" in this Privacy Policy, we are talking both about Device Information and Order Information.
        </p>
      

        <h5>HOW DO WE USE IT:</h5>
        <p>
            a) We use the Order Information that we collect generally to fulfill any orders placed through the Site and app (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations).
            Additionally, we use this Order Information to:
        </p>

        <p>1. Communicate with you;</p>
        <p>2. Screen our orders for potential risk or fraud; and</p>
        <p>3. When in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services.</p>

        <p>
            b) We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site (for example, by generating analytics about how our customers browse and interact with the Site, and to assess the success of our marketing and advertising campaigns).
        </p>

        <!-- <h5>DO NOT TRACK</h5>
    <p>Please note that we do not alter our Site's data collection and use practices when we see a Do Not Track signal from your browser.</p> -->

        <h5>DATA RETENTION AND DELETION</h5>
        <p>When you place an order through the Site, we will maintain your Order Information for our records unless and until you ask us to delete this information. User has all the rights to initiate deletion of their account within the application.</p>

        <h5>CHANGES</h5>
        <p>We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal, or regulatory reasons.</p>

        <h5>CONTACT US</h5>
        <p>For more information about our privacy practices, if you have questions, or if you would like to make a complaint, please contact us by e-mail at <a href="mailto:admin@ashokinfotech.in">Shooppy (Ashok Infotech)</a> or by mail using the details provided below:</p>
        <address>
            Ashok Infotech<br>
            C/610, Titanium city center, 100ft. Anand nagar road,<br>
            Ahmedabad, Gujarat-380015<br>
        </address>
        <p>The Company respects your privacy, and if you do not want to receive any kind of communications from Shooppy (Ashok Infotech) or have any grievances to share, please report to: <a href="mailto:admin@ashokinfotech.in">Shooppy (Ashok Infotech)</a></p>
    </div>
</body>
</html>

src/ShooppyMegaMall.UI/Views/Home/MerchantRefundPolicy.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Privacy Policy</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/StyleSheet1.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1 class="pp-title"> Return & Refund Policy</h1>
        <!-- Section - Improve Your in-Store Experience -->
        <p>Prepaid Orders: The refund for the prepaid order will be processed within 7 working days after receiving your order at the warehouse and Quality Check of the product(s). The Refund Amount will be reflected in the respective payment mode.</p>
        <p>Note: If you've placed a prepaid order using a Refund Coupon, the Value of the Coupon Code will be refunded through a Coupon, and the remaining amount will be paid through your original payment mode.</p>
        <p>For COD Orders: A coupon code of the ordered value will be sent to your registered email address/contact number within 48 hours after receiving your order at the warehouse and Quality Check of the product(s).</p>

        <h4><b>Return &amp; Exchange</b></h4>
        <p>The return or exchange can be done within 12 hrs after your order is delivered. For that, customers need to email us with a proper reason for return.</p>
        <p>In case the customer receives defective/wrong product(s), the reverse pickup will be generated by us, and the shipping charges will be covered by us only.</p>
        <p>Note: It is mandatory to capture a video/photo before shipping the package or handling it to our courier partner.</p>
        <p>If the customer's pin code is non-serviceable by our courier partners, then the customer is liable to self-ship the product(s), and the shipping charges up to ₹100 are 100% refundable if the customer receives defective/wrong product(s).</p>
        <p>Please courier the product(s) to the following address:</p>
        <address>
            Ashok Infotech<br>
            C/610, Titanium city center, 100ft. Anand nagar road,<br>
            Ahmedabad, Gujarat-380015<br>
        </address>
        <p>Kindly pack the product(s) properly to prevent damage during transit. Please ensure the product(s) must be in unused condition with all tags and packaging.</p>
        <p>Note: We suggest you select 'Speed Post' as your courier service rather than using other courier companies. Speed Post is a government-owned entity that operates India's largest postal network and it is totally reliable.</p>

        <h4><b>Things To Consider</b></h4>
        <p>The customers are requested to check the size guide before placing the order.</p>
        <p>The color of the product(s) may vary as per the customer's screen resolution.</p>
        <p>Please provide your WhatsApp registered number for timely updates and a better shopping experience.</p>
        <p>If the customer receives a torn parcel/unrelated product(s)/empty parcel, they are requested to raise a query within 6 hours of delivery. For a safer side, we suggest our customers create an unboxing video of the parcel too.</p>

        <h4><b>Cancellation Policy</b></h4>
        <p>The cancellation request for your order can be done before it confirmed by the seller.</p>
        <p>However, if the product(s) are found to be wrong/damaged, you can raise a return request within 12hrs of order delivery.</p>

    </div>
</body>
</html>

src/ShooppyMegaMall.UI/Views/Home/SearchProduct.cshtml
@model List<ShooppyMegaMall.Application.Models.ProductBasicModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Search Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="product-categori-area">
    <div class="container-fluid">
        <div class="product-categori">
            <div class="row flex-row-reverse">
                <div class="col-lg-12 col-md-12">
                    <div id="content" class="categori-content">
                        <h1 class="page-heading product-listing">
                            <span class="cat-name">Products By Search</span>
                        </h1>
                        <div id="my-tab-content" class="tab-content jump">
                            <div id="grid" class="tab-pane active categoti-grid-view">
                                <div class="row">
                                    @foreach (var product in Model)
                                    {
                                        <div class="col-md-4 col-lg-4 col-sm-6 col-xl-3 mb-3" style="margin-top:25px">
                                            <div class="product-item">
                                                <div class="top-item">
                                                    <a href="@Url.Action("Details","ProductDetail", new {id = product.ProductGuid })" name="productslink">
                                                        <img style="height:244px;width:250px" src="@product.CoverImage" loading="lazy" alt="@product.ProductName">
                                                    </a>
                                                </div>
                                                <div class="bottom-item">
                                                    <div class="product-info">
                                                        <h5><a href="@Url.Action("Details","ProductDetail" , new { id = product.ProductGuid })" name="productslink" class="product_name_Over">@product.ProductName</a></h5>
                                                        <span>₹@product.Price &nbsp;&nbsp;  @if (product.OldPrice != null)
                                                        {<del>₹@product.OldPrice</del>}</span>
                                                        <p>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/ShooppyMegaMall.UI/Views/Home/_BottomBanner.cshtml
@model ShooppyMegaMall.Application.Models.MainModel
<style>
    #bottomimg {
        margin-top: 22px;
    }
</style>
@foreach (var image in Model.BottomBanner.TakeLast(1))
{
    <div class="static-blog-area">
        <div class="container">
            <div class="image-static">
                <div class="row">
                    <div class="col-md-12">
                        <div class="static-blog-image">
                            <a asp-action="AllProducts" asp-route-CategoryId="@image.CategoryId" ><img id="bottomimg" src="@image.Image" loading="lazy" alt="bottombanner" class="lazy"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

src/ShooppyMegaMall.UI/Views/Home/_Logo.cshtml
@model ShooppyMegaMall.Application.Models.MainModel
<div class="logo res">
    <a href="#" name="logolink"><img loading="lazy" src="@Url.Content("~")@Model.CategoryMaster.Logo1" alt="logoimg"></a>
</div>

src/ShooppyMegaMall.UI/Views/Home/_ProductsbyBrand.cshtml
@model ShooppyMegaMall.Application.Models.MainModel
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<div id="grid" class="tab-pane active categoti-grid-view">
    <div class="row">
        @if (Model.ProductdByBrand.Count == 0)
        {
            <img class="" style="margin-top: 3.6pc;" src="/img/no-product-found.jpg" loading="lazy" alt="NoProductFoundimg">
        }
        else
        {
            @foreach (var product in Model.ProductdByBrand)
            {
                <div class="col-md-4 col-lg-4 col-sm-6 col-xl-3" style="margin-top:25px">
                    <div class="product-item">  
                        <div class="top-item">
                            <a href="@Url.Action("Details","ProductDetail", new {id = product.ProductGuid })" name="prodetailspagelink">
                                <img style="height:244px;width:250px" src="@product.Image" loading="lazy" alt="@product.ProductName">
                            </a> 
                        </div>
                        <div class="bottom-item">
                            <div class="product-info">
                                <h5><a href="@Url.Action("Details","ProductDetail" , new { id = product.ProductGuid })" class="product_name_Over" name="productsname">@product.ProductName</a></h5>
                                <span>
                                    ₹@product.Price &nbsp;&nbsp;
                                    @if (product.OldPrice != null)
                                    {
                                        <del>₹@product.OldPrice</del>
                                    }
                                </span> 
                                <p> 
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>
<script>
    $('#removewishlist').hide()
    $('.addWish').click(function (e)
    {
        if ($(e.target).css('color') == 'rgb(255, 0, 0)')
        {
            $(e.target).css('color', 'white');
        }
        else
        {
            $(e.target).css('color', 'red');
        }
  e.preventDefault();
  var el = $(this),
    icon = el.find('i'),
            productId = el.data("product")
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Wishlist", "Wishlist")',
            data: {
                "id": productId
            },
            success: function (data) {
        }
        });
    });
</script>